name: Retrain Model

on:
    push:
        paths:
            - "data/**"
        branches:
            - main

jobs:
    retrain:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v5

            - name: Setup Py
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'

            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            
            - name: Retrain Script
              run: python train.py

            - name: Commit and Push Update
              run: |
                git config --global user.name 'github-actions[bot]'
                git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                git add model.pkl
                git commit -m "Model Auto-Retraining" || echo "No changes to commit."
                git push